
- name: Check if bahmni-mart rpm needs an update
  yum:
    list: bahmni-mart
  register: installed_bahmni_mart
  ignore_errors: true

- name: Uninstall bahmni-mart rpm
  yum: name="bahmni-mart" state=absent
  when: installed_bahmni_mart.results|length != 0 and installed_bahmni_mart.results[0].version != "{{ bahmni_mart_version }}"

- name: Install bahmni-mart using URL
  yum: name="{{ bahmni_mart_url }}" state=present

- name: Copy logback.xml file
  copy:
    src: "{{ role_path }}/files/logback-spring.xml"
    dest: "{{ bahmni_mart_logback_xml_path }}"
    mode: "644"
    owner: "{{ bahmni_user }}"
    group: "{{ bahmni_group }}"

- name: Set bahmni_mart_scdf_schema_name
  set_fact:
    bahmni_mart_scdf_schema_name: 'public'
  when: groups['bahmni-mart-scdf'] is not defined or groups['bahmni-mart-scdf']|length == 0

- name: Copy bahmni-mart config
  template:
    src=application.properties.j2
    dest=/opt/bahmni-mart/properties/application.properties
    mode=644
    owner={{ bahmni_user }}
    group={{ bahmni_group }}

- name: Create bahmni-mart DB User
  postgresql_user:
    db: "{{ analytics_db_name }}"
    name: "{{ analytics_db_user }}"
    password: "{{ analytics_db_password }}"

- name: Create bahmni-mart DB
  postgresql_db:
    name: "{{ analytics_db_name }}"
    owner: "{{ analytics_db_user }}"
  when: passive is not defined or passive !='yes'

- name: Create backup directory
  file:
    path: /data/analytics
    mode: 0666
    owner: "{{ bahmni_user }}"
    group: "{{ bahmni_group }}"
    state: directory

- name: Copy bahmni-mart-backup script
  template:
    src=bahmni-mart-backup.sh.j2
    dest=/opt/bahmni-mart/bin/bahmni-mart-backup.sh
    mode=755
    owner={{ bahmni_user }}
    group={{ bahmni_group }}

- name: Copy bahmni-mart-restore script
  template:
    src=bahmni-mart-restore.sh.j2
    dest=/opt/bahmni-mart/bin/bahmni-mart-restore.sh
    mode=755
    owner={{ bahmni_user }}
    group={{ bahmni_group }}
