- name: Removing recovery config file
  file:
    path=/var/lib/pgsql/{{ postgres_version }}/data/recovery.conf
    state=absent
  when: "{{ inventory_hostname in groups['bahmni-mart-db'] or inventory_hostname in groups['metabase-db'] }}"

- name: Postgres replication setup in slave
  include: slave.yml
  when: "{{ inventory_hostname in groups['bahmni-mart-db-slave'] or inventory_hostname in groups['metabase-db-slave'] }}"

- name: Restart PostgreSQL
  service:
    name=postgresql-{{ postgres_version }}
    state=restarted
  ignore_errors: true